services:
  auth-service:
    build:
      context: ./services/auth
    ports:
      - "8000:8000"
    networks:
      - what-to-eat-network
  menu-service:
    build:
      context: ./services/menu
    ports:
      - "8001:8000"
    networks:
      - what-to-eat-network

  recipe-service:
    build:
      context: ./services/recipe
    ports:
      - "8002:8000"
    networks:
      - what-to-eat-network

  ets-service:
    build:
      context: ./services/eat-together
    ports:
      - "8004:8000"
    networks:
      - what-to-eat-network

  profile-service :
    build:
      context: ./services/profile
    ports:
      - "8005:8000"
    networks:
      - what-to-eat-network

  ui-service:
    build:
      context: ./services/user-interface
    ports:
      - "8006:8000"
    networks:
      - what-to-eat-network

  menu-auto_update-service:
    build:
      context: ./services/menu-auto_update
    networks:
      - what-to-eat-network

networks:
  what-to-eat-network:
    driver: bridge
