[alias]
b = "build"
br = "build --release"
r = "run"
rr = "run --release"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=lld",
    "-C",
    "target-cpu=native",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C",
    "target-cpu=native",
]
